export enum Formats {
  "YYYY-MM-DD" = "YYYY-MM-DD",
  "MM/DD/YY" = "MM/DD/YY",
  "YY/MM/DD" = "YY/MM/DD",
  "DD/MM/YY" = "YY/MM/YY",
  "YYYY-MMDDTHH:MM:SS" = "YYYY-MMDDTHH:MM:SS",
  "YYYYMMDDHHMMSS" = "YYYYMMDDHHMMSS",
  "YYYY-MM-DD HH:MM" = "YYYY-MM-DD HH:MM",
}
